#!/bin/bash
mg2_logo() {
    local logo='
           _ _ _   _
         <  /__ \<  /_   _ _ _ _ _  _ _ _ _   _ _ _ _   _ _  _ _ _ _ _ _ _
         / /__/ // / _ \/ ___/ __ \/ __ `__ \/ __ `__ \/ _ \/ ___/ ___/ _ \
        / // __// /  __/ /__/ /_/ / / / / / / / / / / /  __/ /  / /__/  __/
       /_//____/_/\___/\___/\____/_/ /_/ /_/_/ /_/ /_/\___/_/   \___/\___/
                             _   _ _ _ _ _ _
                           /  |/  / ____/__ \
                          / /|_/ / / __ __/ /
                         / /  / / /_/ // __/
                        /_/  /_/\____//____/
                    _ _ _ _  _ _ _   _ _   _ _  _ _ _
                   / ___/ / / / __ \/ __ \/ _ \/ ___/
                  / /  / /_/ / / / / / / /  __/ /
                 /_/   \__,_/_/ /_/_/ /_/\___/_/

	    Magento 2 Docker Stack environment service installer
    '

    echo -e "\033[1;33m$logo
\033[0m"
}
mg2_logo
sleep 1
cd ~/Documents
mkdir .mymagento && cd .mymagento
git clone https://github.com/zerocool1978/magento2-docker.git
sleep 1
cd magento2-docker/
sleep 1
./archive
sleep 1
./mg2
echo "127.0.0.1   mg121ecommerce.mg2.test
127.0.0.1   traefik.mg2.test
127.0.0.1   dnsmaq.mg2.test
127.0.0.1   mailhog.mg2.test
127.0.0.1   portainer.mg2.test" | sudo tee -a /etc/hosts > /dev/null
sleep 1
#cd ../
#sleep 1
#rm -rf magento2-docker install.run
#sleep 1
cd ~/Documents
