[http.routers]
  [http.routers.https-redirect]
    rule = "HostRegexp(`{any:.*}`)"
    entrypoints = ["http"]
    middlewares = ["https-redirect"]
    service = "https-redirect"
    priority = 1

[http.middlewares]
  [http.middlewares.https-redirect.redirectScheme]
    scheme = "https"

[http.services]
  [http.services.https-redirect.LoadBalancer]
     [[http.services.https-redirect.LoadBalancer.servers]]
        url = "localhost"

[[tls.certificates]]
  certFile = "/etc/ssl/certs/mg2.crt"
  keyFile = "/etc/ssl/private/mg2.key"