#!/usr/bin/env bash

HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

docker build -t "zerocool78/mg2:home" "${HOME}/alpine/"

rm -rf "${HOME}/.docker"

echo
echo "docker push \"zerocool78/mg2:home\""
echo "docker rmi -f \"zerocool78/mg2:home\""