version: "3.5"

services:

  nginx:
    container_name: ${MG2_CFG_DOMAIN_NAME}__nginx
    image: zerocool78/mg2:nginx-${MG2_CFG_NGINX:-1.17}-alpine
    depends_on:
      - db
      - php
    networks:
      default:
        aliases:
          - nginx.${MG2_CFG_DOMAIN_NAME}
      mg2:
        aliases:
          - nginx.${MG2_CFG_DOMAIN_NAME}

  varnish:
    container_name: ${MG2_CFG_DOMAIN_NAME}__varnish
    image: zerocool78/mg2:varnish-${MG2_CFG_VARNISH:-5.2}-alpine
    depends_on:
      - nginx
    labels:
      - traefik.enable=true
      - traefik.http.routers.varnish-${COMPOSE_PROJECT_NAME}.tls=true
      - traefik.http.routers.varnish-${COMPOSE_PROJECT_NAME}.entryPoints=https
      - traefik.http.routers.varnish-${COMPOSE_PROJECT_NAME}.rule=Host(${MG2_CFG_DOMAIN_NAMES})
      - traefik.http.services.varnish-${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=80
    networks:
      default:
        aliases:
          - varnish.${MG2_CFG_DOMAIN_NAME}
      mg2:
        aliases:
          - varnish.${MG2_CFG_DOMAIN_NAME}