version: "3.5"

services:

  nginx:
    environment:
      - UID=${MG2_CFG_UID}
      - GID=${MG2_CFG_GID}
    volumes:
      - ./../../${MG2_CFG_MAGENTO_SRC}/:/var/www/html:ro
      - sock_data:/sock

  php:
    environment:
      - UID=${MG2_CFG_UID}
      - GID=${MG2_CFG_GID}
    volumes:
      - ~/.composer:/var/www/.composer
      - ~/.mg2/ssl/certs:/usr/share/ca-certificates/mg2:ro
      - ./../../${MG2_CFG_MAGENTO_SRC}/:/var/www/html
      - sock_data:/sock

  xdebug:
    environment:
      - UID=${MG2_CFG_UID}
      - GID=${MG2_CFG_GID}
    volumes:
      - ~/.composer:/var/www/.composer
      - ~/.mg2/ssl/certs:/usr/share/ca-certificates/mg2:ro
      - ./../../${MG2_CFG_MAGENTO_SRC}/:/var/www/html
      - sock_data:/sock

volumes:
  sock_data: