#!/usr/bin/env bash

HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

VERSIONS=("4.1" "5.2" "6.2")

for i in "${!VERSIONS[@]}"
do
    docker build -t "zerocool78/mg2:varnish-${VERSIONS[$i]}-alpine" \
        "${HOME}/${VERSIONS[$i]}/alpine/"

    docker tag "zerocool78/mg2:varnish-${VERSIONS[$i]}-alpine" \
        "zerocool78/mg2:varnish-${VERSIONS[$i]}-alpine"
done

rm -rf "${HOME}/.docker"

# Due to docker error "denied: requested access to the resource is denied",
# echoing commands to run them manually instead of running directly
echo

for i in "${!VERSIONS[@]}"
do
    echo "docker push \"zerocool78/mg2:varnish-${VERSIONS[$i]}-alpine\""
    echo "docker rmi -f \"zerocool78/mg2:varnish-${VERSIONS[$i]}-alpine\""
done